# -*- coding: utf-8 -*-
"""IS_practical 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mzzIyzsPxLs2NZWVhNdz0AwXxA_s4hC
"""

!pip -q install pycryptodome

from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad

plaintext = input("Enter the message to encrypt: ")
data = plaintext.encode('utf-8')

key = get_random_bytes(16)

cipher = AES.new(key, AES.MODE_CBC)
iv = cipher.iv

ciphertext = cipher.encrypt(pad(data, AES.block_size))

print("\n========== Encryption ==========")
print("Original Plaintext :", plaintext)
print("Secret Key (Hex)   :", key.hex())
print("Initialization IV  :", iv.hex())
print("Cipher Text (Hex)  :", ciphertext.hex())

decrypt_cipher = AES.new(key, AES.MODE_CBC, iv)

decrypted_data = unpad(
decrypt_cipher.decrypt(ciphertext),
AES.block_size
)
decrypted_text = decrypted_data.decode('utf-8')

print("Decrypted Text:", decrypted_text)

if plaintext == decrypted_text:
 print("\nResult: Encryption and Decryption Successful.")
else:
 print("\nResult: Encryption and Decryption Failed.")

