# -*- coding: utf-8 -*-
"""is_practical_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAtqxRp94WuEiGtMf6JOtXyR7iXmK2DW
"""

# Function for Encryption
def encrypt(text, shift):

    result = ""

    for char in text:
      # Encrypt uppercase letters
        if char.isupper():

            result += chr((ord(char) + shift - 65) % 26 + 65)
    # Encrypt lowercase letters
        elif char.islower():

            result += chr((ord(char) + shift - 97) % 26 + 97)

        else:
            result += char

    return result

# Function for Decryption
def decrypt(text, shift):

    result = ""

    for char in text:

        if char.isupper():

            result += chr((ord(char) - shift - 65) % 26 + 65)

        elif char.islower():

            result += chr((ord(char) - shift - 97) % 26 + 97)

        else:
            result += char

    return result

plaintext = input("Enter Message: ")

shift = int(input("Enter Key Value: "))
ciphertext = encrypt(plaintext, shift)
print("\nEncrypted Message:", ciphertext)
decrypted = decrypt(ciphertext, shift)
print("Decrypted Message:", decrypted)

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
substitution = "QWERTYUIOPASDFGHJKLZXCVBNM"
encrypt_dict = {}

decrypt_dict = {}

# Create Encryption Dictionary

for i in range(len(alphabet)):
    encrypt_dict[alphabet[i]] = substitution[i]

# Create Decryption Dictionary

for i in range(len(alphabet)):
    decrypt_dict[substitution[i]] = alphabet[i]

# Input

plaintext = input("Enter Message: ").upper()

# Encryption

ciphertext = ""

for char in plaintext:

    if char in encrypt_dict:
        ciphertext += encrypt_dict[char]
    else:
        ciphertext += char

print("\nEncrypted Message:", ciphertext)

# Decryption

decrypted = ""

for char in ciphertext:

    if char in decrypt_dict:
        decrypted += decrypt_dict[char]
    else:
        decrypted += char

print("Decrypted Message:", decrypted)

