# -*- coding: utf-8 -*-
"""is_prectical_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMqPO3LIU4Ah8JjFUXLsFuF9ouI2CmLe
"""

import hashlib

def generate_md5(password):

  md5_hash = hashlib.md5(password.encode())
  return md5_hash.hexdigest()

def generate_sha256(password):

  sha_hash = hashlib.sha256(password.encode())
  return sha_hash.hexdigest()

print("========== User Registration ==========")
password = input("Create Password: ")
# Generate hashes
stored_md5 = generate_md5(password)
stored_sha = generate_sha256(password)
print("\nPassword Successfully Stored!\n")
print("Stored MD5 Hash:")
print(stored_md5)
print("\nStored SHA-256 Hash:")
print(stored_sha)

print("\n========== User Login ==========")
login_password = input("Enter Password: ")
# Generate hash of entered password
login_hash = generate_sha256(login_password)
# Compare hashes
if login_hash == stored_sha:
  print("\nLogin Successful!")
  print("Password Verified.")
else:
  print("\nLogin Failed!")
  print("Incorrect Password.")

