# -*- coding: utf-8 -*-
"""is_practical_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MbXvtTPuRP-TgYAibkTE8r-a8upHbUi
"""

from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import serialization, hashes

private_key = rsa.generate_private_key(
public_exponent=65537,   # Standard public exponent
key_size=2048
# RSA Key Size
)

public_key = private_key.public_key()

public_pem = public_key.public_bytes(
encoding=serialization.Encoding.PEM,
format=serialization.PublicFormat.SubjectPublicKeyInfo
)
print(public_pem.decode())

private_pem = private_key.private_bytes(
encoding=serialization.Encoding.PEM,
format=serialization.PrivateFormat.TraditionalOpenSSL,
encryption_algorithm=serialization.NoEncryption()
)
print(private_pem.decode())

message = input("Enter Message : ")
print("\nOriginal Message :", message)

ciphertext = public_key.encrypt(
message.encode(),
padding.OAEP(
mgf=padding.MGF1(algorithm=hashes.SHA256()),
algorithm=hashes.SHA256(),
label=None
)
)
print("\nEncrypted Message (Cipher Text):")
print(ciphertext)

plaintext = private_key.decrypt(
ciphertext,
padding.OAEP(
mgf=padding.MGF1(algorithm=hashes.SHA256()),
algorithm=hashes.SHA256(),
label=None
)
)
print("\nDecrypted Message :")
print(plaintext.decode())

if message == plaintext.decode():
  print("\nRSA Encryption and Decryption Successful.")
else:
  print("\nVerification Failed.")

